---
version: '2'
services:
  database:
    container_name: electron-ota-database
    build:
      context: "."
      dockerfile: db/Dockerfile
    restart: always
    environment:
      MONGO_INITDB_DATABASE: electron-ota
  backend:
    container_name: electron-ota-backend
    build:
      context: "."
      dockerfile: backend/Dockerfile
    restart: always
    command: yarn workspace backend start
    env_file: ".env"
    environment:
      MONGODB_URI: mongodb://database:27017/electron-ota
      CLIENT_ORIGIN: http://${DOCKHERO_HOST}
    ports:
    - 4000:4000
  frontend:
    container_name: electron-ota-frontend
    build:
      context: "."
      dockerfile: frontend/Dockerfile
      args:
        serverUri: http://${DOCKHERO_HOST}:4000/admins
        publicUri: http://${DOCKHERO_HOST}:4000/public
    command: nginx -g "daemon off;"
    ports:
    - 80:80
