{
    "version": "2",
    "services": {
        "backend": {
            "container_name": "electron-ota-backend",
            "build": {
                "context": ".",
                "dockerfile": "backend/Dockerfile"
            },
            "restart": "always",
            "command": "yarn workspace backend start",
            "env_file": [
                "docker.env"
            ],
            "ports": [
                "5600:4000"
            ]
        },
        "frontend": {
            "container_name": "electron-ota-frontend",
            "build": {
                "context": ".",
                "dockerfile": "frontend/Dockerfile",
                "args": {
                    "serverUrl": "localhost:5600/admins"
                }
            },
            "command": "nginx -g \"daemon off;\"",
            "ports": [
                "5500:80"
            ]
        }
    }
}
