---
version: '2'
services:
  database:
    container_name: electron-ota-database
    build:
      context: .
      dockerfile: db/Dockerfile
    restart: always
    environment:
      MONGO_INITDB_DATABASE: electron-ota
  backend:
    container_name: electron-ota-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    command: yarn workspace backend start
    env_file: .env
    environment:
      MONGODB_URI: mongodb://database:27017/electron-ota
      CLIENT_ORIGIN: http://localhost
    ports:
      - 4000:4000
  frontend:
    container_name: electron-ota-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        serverUri: http://localhost/admins
        publicUri: http://localhost/public
    command: nginx -g "daemon off;"
    ports:
      - 3000:3000
  proxy:
    container_name: proxy
    build:
      context: .
      dockerfile: caddy/Dockerfile
    environment:
        HOST: localhost:80
        FRONTEND: frontend:3000
        BACKEND: backend:4000
    ports:
      - 80:80
      - 443:443